# https://hub.docker.com/r/grafana/grafana/tags/
FROM grafana/grafana:5.1.3

COPY configs/datasources /etc/grafana/provisioning/datasources/
COPY configs/dashboards  /etc/grafana/provisioning/dashboards/

ENV GF_SECURITY_ADMIN_PASSWORD=admin \
    GF_SECURITY_ADMIN_USER=admin \
    GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
