{
 "title": "Websites Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP Duration SItes (s)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(probe_http_duration_seconds{instance=~'http.*'}[1m])) BY (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Phase (s)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(probe_http_duration_seconds{instance=~'http.*'}[1m])) BY (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Websites Downtime (%)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_success[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(probe_http_status_code{instance=~'http.*'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (top3)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum(container_memory_rss{container_label_com_docker_swarm_task_name=~\".+\"}) BY (name, instance))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Predict Linear",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_free_bytes{mountpoint=~'/rootfs/mnt.*'}[1h], 8*3600) * 100 / node_filesystem_size_bytes{mountpoint=~'/rootfs/mnt.*'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Websites Total",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{instance=~'http.*'})"
    }
   ]
  },
  {
   "title": "Websites Down",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(probe_success{instance=~'http.*'}) - sum(probe_success{instance=~'http.*'}))"
    }
   ]
  },
  {
   "title": "Websites Request Rates (s)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 35 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~'http.*'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Websites DNS Lookup (s)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{instance=~'http.*'}[15m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Websites SSL Days",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((probe_ssl_earliest_cert_expiry - time()) / (86400))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}