route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'devops'

receivers:
  - name: 'devops'
    slack_configs:
    - channel: tech-alerts
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
      send_resolved: true
      api_url: <slack-url>

