global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'monitor'
rule_files:
    - 'alert.rules.yml'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'engine'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.30.1.160:4999']
  - job_name: "gitlab"
    scrape_interval: 15s
    dns_sd_configs:
      - names: ['tasks.gitlab']
        port: 9090
        type: A
        refresh_interval: 5s
  - job_name: "cadvisor"
    scrape_interval: 5s
    # static_configs:
    #   - targets: ['cadvisor:8080']
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        port: 8080
        type: A
        refresh_interval: 5s
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names: ['tasks.node-exporter']
      type: 'A'
      port: 9100
  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx, tcp_connect, icmp]
    static_configs:
      - targets:
        - https://saidsef.co.uk
        # - https://ide.saidsef.co.uk
        - https://api.saidsef.co.uk
        - https://docker.saidsef.co.uk
        - https://slashnews.co.uk
        - https://jobround.co.uk
        - http://beta.saidsef.co.uk:8083/healthcheck
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

